config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root              'static_pages#home'

  get 'help' =>     'static_pages#help'

  get 'about' =>    'static_pages#about'

  get 'contact' =>  'static_pages#contact'

  get 'signup'  =>    'users#new'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "My Library App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <em>My Library App</em> project by <strong>Peter Jansen</strong>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <!--      <li><a href="http://sites.google.com/">News</a></li> -->
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "My Library App", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The [enter name of library here] Library is here give access to different books
  and other works that the community can access.  The library has many books for
  checkout, as well as reference books that can be used for research.  They cannot
  be checked out, but there are photocopiers which can be used to photocopy the 
  required information.  

  This library also has a video section, which has bluray and dvds for 2 day 
  checkout.  Along with video checkout, there is also a music section with CDs for
  checkout.  

  Along with the media offered, there are also community programs that the library
  offers.  There is a PC users group that meets once a week to discuss different 
  topics in relation to computers.  They also offer training for Microsoft and Adobe
  applications.  Check the event calendar to see what events are up and coming.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  If you need help with the computer, speak to one of our representatives
  at the computer help desk.

  If you need a login for the computer, speak to one of the representatives
  at the computer help desk, and they will help you set up an account here at the
  library.  

  Library hours: 8:00am - 9:00pm Monday through Saturday
  phone: 555-5555 [enter actual number here]
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>If you are having any problems with the system, request help from a librarian.</p>
<p>If you are having issues with the web application, send an email to
  the <a href="mailto:webadmin@librarysys.com">webadmin</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to [enter libary name here] Library</h1>
  <h2>
    This will be the home page for the library system
  </h2>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>